# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Globalping < Formula
  desc ""
  homepage "https://github.com/jsdelivr/globalping-cli"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.2.1/globalping_Darwin_x86_64.tar.gz"
      sha256 "4575f691b85b3ebf96aae0680ea536a539ed3eafa481a1e559b8b44b0ecbded4"

      def install
        bin.install "globalping"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.2.1/globalping_Darwin_arm64.tar.gz"
      sha256 "79d3cd160878d6c5ce8a7d82b1cab75eb9ad7e57fde477ddfa611b0898eb6106"

      def install
        bin.install "globalping"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.2.1/globalping_Linux_x86_64.tar.gz"
      sha256 "495872fd610d67493e4b71f5ac7cb7e5c1b60f2a855c32a6fc66eafac568ad5b"

      def install
        bin.install "globalping"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.2.1/globalping_Linux_arm64.tar.gz"
      sha256 "b0af65892f27a3be2f773b6c5db7089aec4d7d443eba62ca2dca2a78a37eb62a"

      def install
        bin.install "globalping"
      end
    end
  end
end
