# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Globalping < Formula
  desc ""
  homepage "https://github.com/jsdelivr/globalping-cli"
  version "1.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.6.0/globalping_Darwin_x86_64.tar.gz"
      sha256 "975c86828f35e9583bb5fcd63a43ea5515fa93cfcdf7c167d438255be3080c70"

      define_method(:install) do
        bin.install "globalping"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.6.0/globalping_Darwin_arm64.tar.gz"
      sha256 "2b1536ce8ff9736b4102f645e598cfe280e2d390037a49a468f5667af306c20f"

      define_method(:install) do
        bin.install "globalping"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.6.0/globalping_Linux_x86_64.tar.gz"
      sha256 "e1ab93a44573d707cba62a7c67f5a2aaf1ad6dbafc35a2d036026a30fa01401b"
      define_method(:install) do
        bin.install "globalping"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.6.0/globalping_Linux_arm64.tar.gz"
      sha256 "110da15b5290d226c622a9c10f0ff9896b13761d29548ce07e9a7b653c4118d5"
      define_method(:install) do
        bin.install "globalping"
      end
    end
  end
end
