# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Globalping < Formula
  desc ""
  homepage "https://github.com/jsdelivr/globalping-cli"
  version "1.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.5.2/globalping_Darwin_x86_64.tar.gz"
      sha256 "5c1c11887a718ac329f75cd7d44d0b0cb52e6785a04f0648266f2fcb00da976f"

      define_method(:install) do
        bin.install "globalping"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.5.2/globalping_Darwin_arm64.tar.gz"
      sha256 "ee94f0af519e8896aa89d327b4751d7fc31fa57af74e7de46d3f3194d0b60604"

      define_method(:install) do
        bin.install "globalping"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.5.2/globalping_Linux_x86_64.tar.gz"
      sha256 "d4da509136afaf522fae728d172e3fda900fa81a487eef5019d18f8f9cbee743"
      define_method(:install) do
        bin.install "globalping"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsdelivr/globalping-cli/releases/download/v1.5.2/globalping_Linux_arm64.tar.gz"
      sha256 "9b02b04264d4cfa9c7ddd6909033b4c01227a8b9d4c5a5c3f3e4ded746958aeb"
      define_method(:install) do
        bin.install "globalping"
      end
    end
  end
end
